{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "gslb-operator.labels" . | nindent 4 }}
  {{- if and .Values.serviceAccount .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- end }}